import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`bg-zinc-950 text-zinc-50 ${inter.className}`}>
      {/* <div className="-z-[1000] absolute top-[-6rem] right-[10rem] bg-pink-200 rounded-full w-[32.5rem] h-[32.5rem] blur-[10rem] sm:w-[68.9rem] sm:h-[68.9rem]"></div>
      <div className="-z-[1000] absolute top-[-1rem] left-[-35rem] bg-sky-200 rounded-full w-[32.5rem] h-[32.5rem] blur-[10rem] sm:w-[68.9rem] sm:h-[68.9rem]"></div> */}
        {children}
      </body>
    </html>
  )
}
